name: base
channels:
  - pytorch
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_0
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py36_0
  - cffi=1.11.5=py36he75722e_1
  - chardet=3.0.4=py36_1
  - conda=4.5.11=py36_0
  - conda-env=2.6.0=1
  - cryptography=2.4.1=py36h1ba5d50_0
  - freetype=2.9.1=h8a8886c_1
  - idna=2.7=py36_0
  - intel-openmp=2019.1=144
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.35=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - ncurses=6.1=hf484d3e_0
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.15.4=py36h1d66e8a_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - olefile=0.46=py36_0
  - openssl=1.1.1a=h7b6447c_0
  - pillow=5.3.0=py36h34e0f95_0
  - pip=10.0.1=py36_0
  - pycosat=0.6.3=py36h14c3975_0
  - pycparser=2.18=py36_1
  - pyopenssl=18.0.0=py36_0
  - pysocks=1.6.8=py36_0
  - python=3.6.7=h0371630_0
  - readline=7.0=h7b6447c_5
  - requests=2.19.1=py36_0
  - ruamel_yaml=0.15.46=py36h14c3975_0
  - setuptools=40.2.0=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.25.3=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - urllib3=1.23=py36_0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=ha838bed_2
  - pytorch-cpu=0.4.1=py36_cpu_1
  - torchvision-cpu=0.2.1=py36_1
  - pip:
    - absl-py==0.5.0
    - astor==0.7.1
    - autopep8==1.4.1
    - backcall==0.1.0
    - bleach==3.0.2
    - cycler==0.10.0
    - decorator==4.3.0
    - defusedxml==0.5.0
    - entrypoints==0.2.3
    - flake8==3.5.0
    - gast==0.2.0
    - grpcio==1.15.0
    - h5py==2.8.0
    - ipykernel==5.1.0
    - ipython==7.0.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.1
    - jinja2==2.10
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter-client==5.2.3
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - keras==2.2.2
    - keras-applications==1.0.4
    - keras-preprocessing==1.0.2
    - kiwisolver==1.0.1
    - markdown==3.0.1
    - markupsafe==1.0
    - matplotlib==3.0.0
    - mccabe==0.6.1
    - mistune==0.8.4
    - nbconvert==5.4.0
    - nbformat==4.4.0
    - networkx==2.2
    - notebook==5.7.0
    - numpy-stl==2.7.0
    - pandas==0.23.4
    - pandas-profiling==1.4.1
    - pandocfilters==1.4.2
    - parso==0.3.1
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - prometheus-client==0.4.2
    - prompt-toolkit==2.0.6
    - protobuf==3.6.1
    - ptyprocess==0.6.0
    - pycodestyle==2.4.0
    - pyflakes==1.6.0
    - pygments==2.2.0
    - pyparsing==2.2.2
    - python-dateutil==2.7.3
    - python-utils==2.3.0
    - pytz==2018.5
    - pyyaml==3.13
    - pyzmq==17.1.2
    - qtconsole==4.4.2
    - rope==0.11.0
    - scikit-learn==0.20.0
    - scipy==1.1.0
    - seaborn==0.9.0
    - send2trash==1.5.0
    - simplegeneric==0.8.1
    - sklearn==0.0
    - stl==0.0.3
    - tensorboard==1.11.0
    - tensorflow==1.11.0
    - termcolor==1.1.0
    - terminado==0.8.1
    - testpath==0.4.2
    - torch==0.4.1
    - torchvision==0.2.1
    - tornado==5.1.1
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - werkzeug==0.14.1
    - widgetsnbextension==3.4.2
prefix: /home/francesco/miniconda3

